<?php declare(strict_types = 1);

/**
 * @file
 * Functions to support theming in the Spark theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function spark_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function spark_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function spark_preprocess_node(array &$variables): void {

}
